global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'metrics-agent'
    static_configs:
      - targets: ['metrics-agent:8080']   # профилем local можно оставить host.docker.internal:8080
    metrics_path: /actuator/prometheus

  - job_name: 'metrics-aggregator'
    static_configs:
      - targets: ['metrics-aggregator:8080']
    metrics_path: /actuator/prometheus